name = input("Enter Student Name: ")
std = input("enter the std: ")
age = input("what is your age: ")
gender = input("what is your gender: ")
goal = input("what is your goal: ")
study_hour = input("what is your study hour:")
hobby = input("tell me about your hobby:")
fear = input("what is ur fear for your goal: ")
strength = input("what is your strength: ")
description = input("Do you want to say anything else?: ")
dream_income = input("What is your dream monthly income: ")
print("AI TUTOR FOUNDATION REPORT")
print("Name:", name)
print("Class:", std)
print("Age:", age)
print("gender", gender)
print("goal", goal)
print("study_hour", study_hour)
print("hobby", hobby)
print("fear", fear)
print("strength", strength)
print("description", description)
print("dream_income", dream_income)
print("+" * 40)
print("AI TUTOR FOUNDATION REPORT")
print("+" * 40)
