print("-" * 35)
print("     Smart Task Prioritizer")
print("-" * 35)
user_name = input("Enter your name: ")
today_date = input("Enter today's date: ")
task_name = input('Enter the task name: ')
priority = int(input("Enter priority at least(1-5):"))
estimated_hours = float(input("Enter estimated hours:"))
print("-" * 35)
print("      Task Summary")
print("-" * 35)
print("Name:", user_name)
print("Date:", today_date)
print("Task:", task_name)
print("Priority:", priority)
print("Estimated Hours:", estimated_hours)
