print("=" * 40)
print("         PLANET EXPLORER PROFILE")
print("=" * 40)
planet_name = input("Enter the planet Name: ")
galaxy_name = input("Enter the galaxy: ")
distance_from_earth = float(input("Enter the Distance From Earth: "))
number_of_moons = int(input("Enter The Number of The Moon: "))
gravity = float(input("Enter The Gravity: "))
average_temperature = float(input("Enter The Temprature: "))
atmosphere = input("Enter The Atomosphere: ")
oxygen_percentage = float(input("What is The oxygen Level: "))
water_available = input("Water is avalible: ")
print("=" * 40)
print("        PLANET REPORT")
print("=" * 40)
print("planet:", planet_name)
print("Galaxy:", galaxy_name)
print("distance from earth:", distance_from_earth, "light year")
print("number of moons:", number_of_moons)
print("gravity:", gravity, "G")
print("average temperature:", average_temperature, "°C")
print("atmosphere:", atmosphere)
print("oxygen percentage:", oxygen_percentage, "%")
print("water available:", water_available)
